# <h1>.eslintrc.yml - Configure ESLint for this project</h1>
env:
    browser: true
    es2020: true
extends:
    - standard
    # <p>See the <a
    #         href="https://github.com/prettier/eslint-config-prettier#installation">ESLint
    #         config prettier docs</a> and its parent link, <a
    #         href="https://prettier.io/docs/en/integrating-with-linters.html">integrating
    #         Prettier with linters</a>.</p>
    - prettier
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
plugins:
    - "@typescript-eslint"
rules:
    camelcase: off
    # <p>TypeScript already enforces this; otherwise, eslint complains that
    #     <code>NodeJS</code> is undefined. See <a
    #         href="https://github.com/Chatie/eslint-config/issues/45#issuecomment-1003990077">this
    #         GitHub issue</a>.</p>
    no-undef: off
