# Copyright (C) 2023 Bryan A. Jones.
#
# This file is part of the CodeChat Editor.
#
# The CodeChat Editor is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# The CodeChat Editor is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# the CodeChat Editor. If not, see
# [http://www.gnu.org/licenses/](http://www.gnu.org/licenses/).
#
# # `Cargo.toml` -- Rust build/package management config
[package]
name = "server"
version = "0.1.0"
edition = "2021"

# This library allows other packages to use core CodeChat Editor features.
[lib]
name = "code_chat_editor"

# See more
# [keys and their definitions](https://doc.rust-lang.org/cargo/reference/manifest.html).
[dependencies]
actix-files = "0.6"
actix-web = "4"
lazy_static = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
urlencoding = "2"
# Per the <a>docs</a>, avoid building the binary.
pulldown-cmark = { version = "0.9", default-features = false }
# [Windows-only dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies).
[target.'cfg(windows)'.dependencies]
win_partitions = "0.3.0"

[dev-dependencies]
# See the [docs](https://github.com/rust-lang/rust-clippy#usage) to install
# clippy; it can't be installed as a dev-dependency. See the
# [fmt docs](https://github.com/rust-lang/rustfmt#quick-start) to install fmt.
#clippy = "0.0.302"

# Code coverage, the manual way:
#
# 1. Run `cargo install rustfilt` per the [code coverage docs](https://doc.rust-lang.org/rustc/instrument-coverage.html#building-the-demangler).
# 2. You must manually run `rustup component add llvm-tools-preview` following the [coverge docs](https://doc.rust-lang.org/rustc/instrument-coverage.html#installing-llvm-coverage-tools). Per some searching, also run `cargo install cargo-binutils` to put these tools in the path.
# 3. In Powershell, `$Env:RUSTFLAGS = "-C instrument-coverage"` then `cargo test`. When the tests run, record the name of the test binary.
# 4. `rust-profdata merge -sparse default_*.profraw -o default.profdata`.
# 5. `rust-cov show --Xdemangler=rustfilt target\debug\deps\code_chat_editor-4dbe5c7815a53cd9.exe --instr-profile=default.profdata --ignore-filename-regex=\\.cargo\\registry --format=html --output-dir=coverage`, replacing the binary path with the one recorded in step 3.
# 6. Open the file `coverage\index.html`.
#
# Or, `cargo install cargo-tarpaulin` then `cargo tarpaulin --ignore-panics --out=html --skip-clean`.

# See https://doc.rust-lang.org/cargo/reference/features.html.
[features]
# Uncomment this to show an explanation of the lexing process.
#default = ["lexer_explain"]
lexer_explain = []
